import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Drawer, Navbar, ThemeProvider, QueryProvider } from '@/components';
import { DrawerItem } from '@/types';
import { RiDashboard3Line, RiGroup2Fill, RiUser3Fill } from 'react-icons/ri';
import { ROUTES } from '@/routes';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'RCM',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const Items: DrawerItem[] = [
    {
      label: 'Dashboard',
      icon: <RiDashboard3Line size={26} />,
      href: ROUTES.DASHBOARD,
    },
    {
      label: 'Miembros',
      icon: <RiUser3Fill size={26} />,
      href: ROUTES.MEMBERS,
    },
    { label: 'Celulas', icon: <RiGroup2Fill size={26} />, href: ROUTES.CELLS },
    {
      label: 'Sectores',
      icon: <RiGroup2Fill size={26} />,
      href: ROUTES.SECTORS,
    },
    {
      label: 'Subsectores',
      icon: <RiGroup2Fill size={26} />,
      href: ROUTES.SUBSECTORS,
    },
    {
      label: 'Reportes',
      children: [
        { label: 'Semanal', href: ROUTES.REPORTS.WEEKLY },
        { label: 'Metas', href: ROUTES.REPORTS.GOALS },
        { label: 'Cuatrimestral', href: ROUTES.REPORTS.QUARTERLY },
        { label: 'Anual', href: ROUTES.REPORTS.ANNUAL },
      ],
    },
  ];
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <ThemeProvider>
            <Drawer items={Items}>
              <Navbar />
              <main>{children}</main>
            </Drawer>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
